# Generated by Django 5.1.3 on 2025-06-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_category_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
