# Generated by Django 5.1.3 on 2025-06-17 18:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='item_name',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'item_name')},
        ),
    ]
