# Generated by Django 5.2.3 on 2025-07-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_product_review_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='item_category',
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.ManyToManyField(to='shop.category'),
        ),
    ]
