# Generated by Django 5.2.3 on 2025-08-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_item_item_category_item_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
